import Head from "next/head";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
  AiFillGithub,
  AiFillInstagram,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import devroque from "../public/roque_dev.png";
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import Image from "next/image";
import web1 from "../public/bgdg.jpg";


export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Roque Costa Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">Roque Costa Dev</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="#"
                >
                  Resumo
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Roque Costa
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Desenvolvedor Frontend React
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              Desenvolvedor Frontend e estudante de Engenharia da Computação, com experiência 
              profissional em React - Redux, Thunk, Next. Além de Backend com Node - Knex, PostgreSQL.
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <a href="https://instagram.com/roquectx" rel="no-opener no-referrer" target="_blank"><AiFillInstagram /></a>
              <a href="https://www.linkedin.com/in/roque-souza-costa-6aa8171ba/?originalSubdomain=br" rel="no-opener no-referrer" target="_blank"><AiFillLinkedin /></a>
              <a href="https://www.github.com/RockVoid" rel="no-opener no-referrer" target="_blank"><AiFillGithub /></a>
            </div>
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={devroque} layout="fill" objectFit="cover" />
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Meus Serviços</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Desde o inicio da minha jornada com desenvolvedor, sempre busquei
              melhorar minhas habilidades dentro dos times que eu participei.
              Sejam eles na <span className="text-teal-500">faculdade </span>
              ou na <span className="text-teal-500">Bluecore</span>
              , sempre agreguei valor as entregas e a entender o que era solicitado.
              Além de entregar tudo no tempo certo {`:]`}.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Minhas principais Hard Skills são o domínio de Design de Layouts com Tailwind,
              e Figma. Além de integração de API'S com o Front, sendo elas feitas por mim ou não.
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image src={design} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2  ">
                Figma Designer
              </h3>
              <p className="py-2">
                Projeção de Layouts
              </p>
              <h4 className="py-4 text-teal-600">Ferramentas que uso</h4>
              <p className="text-gray-800 py-1">Figma</p>
              <p className="text-gray-800 py-1">Unsplash</p>
              <p className="text-gray-800 py-1">Google Fonts</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={code} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">
                Dê vida ao seu projeto dos sonhos.
              </h3>
              <p className="py-2">
                Com uma regra de negócio bem definida. Posso dar vida a projetos de Software.
              </p>
              <h4 className="py-4 text-teal-600">Tecnologias</h4>
              <p className="text-gray-800 py-1">React JS</p>
              <p className="text-gray-800 py-1">Node JS</p>
              <p className="text-gray-800 py-1">PostgreSQL</p>
              <p className="text-gray-800 py-1">Heroku</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={consulting} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">Faculdade</h3>
              <p className="py-2">
                Ainda universitário, possuo também conhecimentos teóricos sobre o mundo da computação.
                Me considero aberto a novas tecnologias e áreas.
              </p>
              <h4 className="py-4 text-teal-600">Áreas de interesse</h4>
              <p className="text-gray-800 py-1">Desenvolvimento Web</p>
              <p className="text-gray-800 py-1">Ciência de Dados</p>
              <p className="text-gray-800 py-1">Softwares Corporativos</p>
            </div>
          </div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Portfólio</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Aqui vão alguns projetos que agreguei tanto no meio corporativo quanto
              projetos pessoais e universitarios!
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-col lg:flex-wrap">
            <div class="bg-white w-1/2 rounded overflow-hidden shadow-lg">
              <div class="px-6 py-4">
                <div class="font-bold text-xl mb-2">Bluecore - 8 meses</div>
                <p class="text-gray-700 text-base">
                  Na Blue, atuei majoritariamente com Node Js e algumas aplicações Frontend. 
                  Ficava responsável por integrar sistemas como o Rituaali e o Plonge, tendo máxima
                  atenção com Design e lógica de componentes. 
                </p>
              </div>
              <div class="px-6 pt-4 pb-2">
                <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">#NodeJS</span>
                <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">#PostgreSQl</span>
              </div>
            </div>
          </div>
          <div class="bg-white w-1/2 rounded overflow-hidden shadow-lg">
            <div class="px-6 py-4">
              <div class="font-bold text-xl mb-2">Chefeeder - Atualmente</div>
              <p class="text-gray-700 text-base">
                Chefeeder é um projeto que busca automatizar os pedidos, administração 
                de clientes e finanças de restaurantes na Grande Fortaleza, o Projeto, feito em React,
                ainda não chegou na 1.0.
              </p>
            </div>
            <div class="px-6 pt-4 pb-2">
              <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">#React</span>
              <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">#Material UI</span>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
